target_include_directories(${PROJECT_NAME} PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/${PROJECT_NAME}>
  $<INSTALL_INTERFACE:include/${PROJECT_NAME}> 
)

install(TARGETS ${PROJECT_NAME}
  EXPORT ${PROJECT_NAME}-config
  LIBRARY DESTINATION lib
  INCLUDES DESTINATION include
  PUBLIC_HEADER DESTINATION include/gazebo_bridge)
install(EXPORT ${PROJECT_NAME}-config
  DESTINATION lib/cmake/${PROJECT_NAME}
  EXPORT_LINK_INTERFACE_LIBRARIES)
