#################################
# PID parameters for pose seeking
#################################

# Maximum value of error integral for all PID controllers
windup_limit: 0.05

# PID gains
x_proportional_gain: 1.0
y_proportional_gain: 1.0
z_proportional_gain: 1.0
x_integral_gain: 0.01
y_integral_gain: 0.01
z_integral_gain: 0.01
x_derivative_gain: 0.001
y_derivative_gain: 0.001
z_derivative_gain: 0.001

angular_proportional_gain: 0.02
angular_integral_gain: 0.01
angular_derivative_gain: 0.001
