<?xml version="1.0"?>

<!-- TODO(sara): rename robot name to crane_x7_with_tools -->
<robot name="crane_x7"
       xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <xacro:include filename="$(find crane_x7_description)/urdf/crane_x7.xacro" />

  <link name="base_link" />
  <link name="world" />

  <joint name="base_link_to_world_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <xacro:arg name="use_effort_gripper" default="true" />

  <xacro:crane_x7 parent="base_link"
                  base_color="red"
                  shoulder_color="white"
                  shoulder_joint_cover_color="red"
                  upper_arm_upper_color="white"
                  upper_arm_lower_color="white"
                  elbow_joint_cover_color="red"
                  lower_arm_upper_color="white"
                  lower_arm_lower_color="white"
                  wrist_color="white"
                  hand_color="red"
                  joints_vlimit="4.81710873"
                  shoulder_llimit="-2.97132"
                  shoulder_ulimit="2.97132"
                  logos_definition="$(find crane_x7_description)/urdf/crane_x7_rt_logos.xacro"
                  use_effort_gripper="$(arg use_effort_gripper)">
    <origin xyz="0 0 0"/>
  </xacro:crane_x7>

  <xacro:property name="tool_length" value="0.3" />
  <xacro:property name="tool_radius" value="0.003" />
  <xacro:property name="tool_position_x" value="0.01" />
  <xacro:property name="tool_position_z" value="${tool_length/2}" />
  <xacro:property name="tool_orientation_p" value="0.02" />
  <!-- TODO(sara): resolve collision probrem -->
  <xacro:property name="tool_end_position_z" value="0.39" />

  <link name="tool_link">
    <visual>
      <origin rpy="0 -${tool_orientation_p} 0" xyz="${tool_position_x} 0 -${tool_position_z}"/>
      <geometry>
        <cylinder radius="${tool_radius}" length="${tool_length}"/>
      </geometry>
    </visual>
    <visual>
      <origin rpy="0 ${tool_orientation_p} 0" xyz="-${tool_position_x} 0 -${tool_position_z}"/>
      <geometry>
        <cylinder radius="${tool_radius}" length="${tool_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 -${tool_orientation_p} 0" xyz="${tool_position_x} 0 -${tool_position_z}"/>
      <geometry>
        <cylinder radius="${tool_radius}" length="${tool_length}"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="0 ${tool_orientation_p} 0" xyz="-${tool_position_x} 0 -${tool_position_z}"/>
      <geometry>
        <cylinder radius="${tool_radius}" length="${tool_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="tool_link_to_gripper_base_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${tool_end_position_z}"/>
    <parent link="crane_x7_gripper_base_link" />
    <child link="tool_link" />
  </joint>

</robot>
