<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="tools">

    <xacro:property name="tool_length" value="0.27" />
    <xacro:property name="tool_radius" value="0.002" />
    <xacro:property name="tool_position_x" value="0.012" />
    <xacro:property name="tool_position_z" value="${tool_length/2}" />
    <xacro:property name="tool_orientation_p" value="0.05" />
    <xacro:property name="tool_end_position_z" value="0.325" />
    
    <link name="tool_link">
      <visual>
        <origin rpy="0 -${tool_orientation_p} 0" xyz="${tool_position_x} 0 -${tool_position_z}"/>
        <geometry>
          <cylinder radius="${tool_radius}" length="${tool_length}"/>
        </geometry>
      </visual>
      <visual>
        <origin rpy="0 ${tool_orientation_p} 0" xyz="-${tool_position_x} 0 -${tool_position_z}"/>
        <geometry>
          <cylinder radius="${tool_radius}" length="${tool_length}"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 -${tool_orientation_p} 0" xyz="${tool_position_x} 0 -${tool_position_z}"/>
        <geometry>
          <cylinder radius="${tool_radius}" length="${tool_length}"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 ${tool_orientation_p} 0" xyz="-${tool_position_x} 0 -${tool_position_z}"/>
        <geometry>
          <cylinder radius="${tool_radius}" length="${tool_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 -${tool_position_z}" />
        <mass value="0.01" />
        <inertia  ixx="0.0" ixy="0.0"  ixz="0.0"  iyy="0.0"  iyz="0.0"  izz="0.0" />
      </inertial>
    </link>

    <joint name="tool_link_to_gripper_base_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 ${tool_end_position_z}"/>
      <parent link="crane_x7_gripper_base_link" />
      <child link="tool_link" />
    </joint>

    <gazebo reference="tool_link">
      <material>Gazebo/WoodFloor</material>
    </gazebo>
    <gazebo reference="tool_link_to_gripper_base_joint">
      <preserveFixedJoint>true</preserveFixedJoint>
    </gazebo>

  </xacro:macro>
</robot>
